config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
    
  devise_for :users, :controllers => {
    :registrations => 'registrations'
  }
  
  resources :topics do
    resources :posts, except: [:index]
  end
  
  get 'faq' => 'welcome#faq'
  
  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :topic
    has_many :comments, dependent: :destroy
    
    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :topic, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, dependent: :destroy
    
    validates :name, length: { minimum: 5 }, presence: true
    validates :description, length: { minimum: 15 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def index
  #   @posts = Post.all
  # end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])
    
    @post.topic = @topic
    
    if @post.save
      flash[:notice] = 'Post was saved!'
      redirect_to [@topic, @post]
    else
      flash.now[:alert] = "Something went wrong, please try again..."
      render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    p @post
    @post.title = params[:post][:title]
    p @post.title
    @post.body = params[:post][:body]
    
    if @post.save
      flash[:notice] = "Your post was updated!"
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "Sorry, there was an issue, Try again.."
      render :edit
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
   
   private
   
   def sign_up_params
        params.require(:user).permit(
            :name,
            :email,
            :password,
            :password_confirmation )
   end
   
   def account_update_params
        params.require(:user).permit(
            :name,
            :email,
            :password,
            :password_confirmation,
            :current_password )       
   end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    
    def index
        @topics = Topic.all
    end
    
    def show
        @topic = Topic.find(params[:id])
    end
    
    def new
        @topic = Topic.new 
    end
    
    def create
        @topic = Topic.new
        @topic.name = params[:topic][:name]
        @topic.description = params[:topic][:description]
        @topic.public = params[:topic][:public]
        
        if @topic.save
           redirect_to @topic, notice: "Topic #{@topic.id} was created"
        else
            flash.now[:alert] = "Error, please try again.."
            render :new
        end
    end
    
    def edit
        @topic = Topic.find(params[:id])
    end
    
    def update
       @topic = Topic.find(params[:id]) 
       
       @topic.name = params[:topic][:name]
       @topic.description = params[:topic][:description]
       @topic.public = params[:topic][:public]
       
        if @topic.save
            flash[:notice] = "Topic was updated!"
            redirect_to @topic
        else
            flash.now[:alert] = "Error saving Topic, please try again.."
            render :edit
        end
    end
    
    def destroy
        @topic = Topic.find(params[:id])
        
        if @topic.destroy
           flash[:notice] = "Topic #{@topic.id} was successfully deleted"
           redirect_to action: :index
        else
            flash.now[:alert] = "Something went wrong, please try again.."
            render :show
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end

  def about
    
  end
  
  def faq
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def form_group_tag(errors, &block)
       css_class = 'form-group'
       css_class << ' has error' if errors.any?
       
       content_tag :div, capture(&block), class: css_class
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,700" rel="stylesheet">
  </head>
  <body>
    
    <div class='container'>
        <ul class='nav nav-links'>
          <li class="head-logo">
            <%= link_to 'MCC', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Topics', topics_path %></li>
          <li><%= link_to 'FAQ', faq_path %></li>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        </ul>
    
      
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      
      <!--<p class="notice"><%= notice %></p>-->
      <!--<p class="alert"><%= alert %></p>-->
          
      <%= yield %>
    </div>
  
    <!--<footer>-->
    <!--  <p>-->
    <!--    made by <%= link_to "Kai Brabo", "https://www.github.com/kaibrabo", {:class => "footer-link"} %>-->
    <!--  </p>-->
    <!--</footer>-->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@topic, @post] do |f| %>
   <% if post.errors.any? %>
       <div class='alert alert-danger'>
           <h4><%= pluralize(post.errors.count, 'error') %></h4>
           
           <ul>
               <% post.errors.full_messages.each do |msg| %>
                   <li><%= msg %></li>
               <% end %>
           </ul>
       </div>
   <% end %>
   
    <%= form_group_tag(post.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'type title' %>
    <% end %>
    
    <%= form_group_tag(post.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'type details' %>
    <% end %>
    
    <div class="form-group">
        <%= f.submit "Save", class: 'save-post-link' %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class="edit-post">
 <h2>Edit Post</h2>
 
   <div class="post-rules">
     <p>Post Guidelines</p>
     <ol>
       <li class="post-rules-item">i.e. <em>- Eldridge Grade, 3:15pm (or 15:15), fireroad washed away near top </em></li>
       <li class="post-rules-item">only state facts, please leave opinions to yourself.</li>
     </ol>
   </div>
   
   <div class="post-input">
       <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>

</div>

app/views/posts/new.html.erb
<div class="new-post">
 <h3>Create Post</h3>
 
   <div class="post-rules">
     <p>Post Guidelines</p>
     <ol>
       <li class="post-rules-item">i.e. <em>- Eldridge Grade, 3:15pm (or 15:15), fireroad washed away near top </em></li>
       <li class="post-rules-item">only state facts, please leave opinions to yourself.</li>
     </ol>
   </div>
   
   <div class="post-input">
       <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>

</div>

app/views/posts/show.html.erb
<div class="show-post">
    <h4 class="show-post-id">
        Post ID: <%= params[:id] %>
    </h4>
    
    
    <div class="show-post-details">
        <p>
            <em>made: <%= @post.created_at.strftime("%b %d, '%y") %></em>
        </p>
        <h3 class='post-title'>
            <strong><%= @post.title %></strong>
        </h3>
        <h4 class='post-body'>
            <%= @post.body %>
        </h4>
    </div>
    
    <div class="show-post-edit-delete">
        <h5>
            <%= link_to 'Edit', edit_post_path(@post.topic, @post), class: 'edit-post-link' %>
        </h5>
        <h5>
            <%= link_to 'Delete', [@post.topic, @post], method: :delete, class: 'delete-post-link', data: {confirm: "Are you sure you want to delete this post?"} %>
        </h5>
    </div>
    
</div>

app/views/topics/_form.html.erb
<%= form_for [@topic] do |f| %>
   <% if topic.errors.any? %>
       <div class='alert alert-danger'>
           <h4><%= pluralize(topic.errors.count, 'error') %></h4>
           
           <ul>
               <% topic.errors.full_messages.each do |msg| %>
                   <li><%= msg %></li>
               <% end %>
           </ul>
       </div>
   <% end %>
   
    <%= form_group_tag(topic.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'type name' %>
    <% end %>
    
    <%= form_group_tag(topic.errors[:description]) do %>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: 'type details' %>
    <% end %>
    
    <div class="form-group">
        <%= f.submit "Save", class: 'save-topic-link' %>
    </div>
<% end %>

app/views/topics/edit.html.erb
<div class="edi-topic">
 <h3>Create topic</h3>
 
   <div class="topic-rules">
     <p>topic Guidelines</p>
     <ol>
       <li class="topic-rules-item">ex. <em><strong> Marin County - China Camp State Park </strong></em></li>
       <li class="topic-rules-item">only state facts, please leave opinions to yourself.</li>
     </ol>
   </div>
   
   <div class="topic-input">
      <%= render partial: 'form', locals: { topic: @topic } %>
   </div>

</div>

app/views/topics/index.html.erb
<div class="all-topics">
   <h2 class="all-topics-title">Topics</h2>
   
    <h5>
        <%= link_to 'Create Topic', new_topic_path, {:class => 'new-topic-link'} %>
    </h5>

    <% @topics.reverse.each { |t| %>
    
            <div class='index-topic'>
                <p class="topic-info">
                    <strong><%= link_to truncate(t.name, length: 20), t , {:class => 'topic-details'}%></strong>
                </p>
                <p class="topic-time">
                    <em><%= t.created_at.strftime("%b %d, %Y") %></em>
                </p>
                <p>
                    <%= link_to truncate(t.description, length: 30), t , {:class => 'topic-details'}%>
                </p>
            </div>
    
    <% } %> 
</div>

app/views/topics/new.html.erb
<div class="new-topic">
 <h3>Create topic</h3>
 
   <div class="topic-rules">
     <p>topic Guidelines</p>
     <ol>
       <li class="topic-rules-item">ex. <em><strong> Marin County - China Camp State Park </strong></em></li>
       <li class="topic-rules-item">only state facts, please leave opinions to yourself.</li>
     </ol>
   </div>
   
   <div class="topic-input">
      <%= render partial: 'form', locals: { topic: @topic } %>
   </div>

</div>

app/views/topics/show.html.erb
<div class="show-topic">
    <h4 class="show-topic-id">
        Topic ID: <%= params[:id] %>
    </h4>
    
    <!--  Topic Details -->
    <div class="show-topic-details">
        <p>
            <em>made: <%= @topic.created_at.strftime("%b %d, %Y") %></em>
        </p>
        <h3 class='topic-title'>
            <strong><%= @topic.name %></strong>
        </h3>
        <h4 class='topic-body'>
            <%= @topic.description %>
        </h4>
    </div>
    
    <!-- EDIT & DELETE buttons-->
    <div class="show-topic-edit-delete">
        <h5>
            <%= link_to 'Edit', edit_topic_path, class: 'edit-topic-link' %>
        </h5>
        <h5>
            <%= link_to 'Delete', @topic, method: :delete, class: 'delete-topic-link', data: {confirm: "Are you sure you want to delete this topic?"} %>
        </h5>
    </div>
    
    <!-- Topic Posts -->
    <div class="topic-posts">
        <div class="all-posts">
           <h2 class="all-posts-title">Posts</h2>
            
            <h5>
                <%= link_to 'Create Post', new_topic_post_path(@topic), {:class => 'new-post-link'} %>
            </h5>
        
            <% @topic.posts.reverse.each { |p| %>
            
                    <div class='index-post'>
                        <p class="post-info">
                            <strong><%= link_to p.title, topic_post_path(@topic, p) , {:class => 'post-details'}%></strong>
                        </p>
                        <p class="post-time">
                            <em><%= p.created_at.strftime("%b %d, %Y") %></em>
                        </p>
                        <p>
                            <%= link_to truncate(p.body, length: 30), p , {:class => 'post-details'}%>
                        </p>
                        
                        <h4>
                            <%= p.comments.count %> comments
                        </h4>
                    </div>
            
            <% } %> 
        </div>
    </div>
    
</div>

app/views/welcome/about.html.erb
<div class="header-about">
    <h3>
        Join our community!
    </h3>
    
    <h4>
        Who we are:
    </h4>
    
    <ul>
        <li>County-concious riders who understand the local scene's rules and regulations</li>
        <li>Helpful memebers willing to support others</li>
        <li>Knowledgable, Eco-Concious, and Motivated</li>
    </ul>
</div>

app/views/welcome/faq.html.erb
<div class="header-faq">
    <h2>Frequently Asked Questions</h2>
    <p>
        <strong>
            How do I Join?
        </strong>
    </p>
    
    <p>
        <em>
            <ol>
                <li>Click "Sign Up" at the top right of the page</li>
                <li>Make a profile</li>
                <li>Ride and connect with other riders</li>
            </ol>
        </em>
    </p>
    
    <p>
        <strong>
            What if I don't ride?
        </strong>
    </p>
    
    <p>
        <em>
            Ask yourself:
            <ol>
                <li>'Will I ride on the road*, or will I ride on the dirt*?'</li>
                <li>'Do I want to wear lycra/spandex*, or moto shorts/jersey*?'</li>
                <li>'Do I drink wine* or beer* on a Friday?'</li>
            </ol>
            <p>... if you answered <strong>YES</strong> to the first options of each, you'll ride road! You Spandex Warrior!</p>
            <p>otherwise, head to your local shop and pick up a Mountain bike and six-pack, sit back and sip a cold one on the trail.</p>
    
    
    <p>
        <strong>
            Where can I ride?
        </strong>
    </p>
    
    <p> 
        Road:
        <em>
            <ul>
                <li>Everywhere! BEWARE of cars, though.</li>
                <li>West Marin via Sir Francis Drake blvd. to CA hwy 1 in Olema, right to Pt. Reyes Station, then to Nicasio back onto SFD blvd.</li>
                <li>CA hwy 1 from Mill Valley to Muir Beach, to Mt Tamalpais, out to Stinson Beach, and back up Mt Tamalpais into MV</li>
            </ul>
        </em>
        
        Mountain:
        <em>
            <ul>
                <li>China Camp State Park ($3 fee)</li>
                <li>Tamarancho (Yearly Pass req.)</li>
                <li>Stafford Lake Bike Park ($5-10 for parking)</li>
            </ul>
        </em>
    </p>
</div>

app/views/welcome/index.html.erb
<div class="header-welcome">
    <h2 class="index-header">
        Marin County Cycling
    </h2>
    
    <h3>
        Mission:
    </h3>
    <p>"We are the riders of Marin County, and we are going to ride until everyone is on a bike!"</p>
    
    
    <h3 class="login-signup">
        Login or Sign Up
    </h3>
    
    <div class="google-signin">
        
    </div>
</div>